[package]
name = "bevy_pbr_generator"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy = { version = "0.19", features = [
    "bevy_feathers",
    "file_watcher",
    "png",
    "pbr_transmission_textures",
    "pbr_specular_textures",
    "pbr_anisotropy_texture",
    "pbr_multi_layer_material_textures",
] }
clap = { version = "4.4", features = ["derive"] }
half = "2"
image = { version = "0.24", default-features = false, features = ["png"] }
glam = "0.24"

[dev-dependencies]
naga_oil = "0.22"
naga = "29"
