[package]
name = "bevy_pbr_generator"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy = { version = "0.19", features = [
    "bevy_feathers",
    "file_watcher",
    "pbr_anisotropy_texture",
    "pbr_multi_layer_material_textures",
    "pbr_specular_textures",
    "pbr_transmission_textures",
] }
bytemuck = "1.25"
half = "2.7"
image = { version = "0.25", default-features = false, features = ["png"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
